### PR TITLE
SG-155 sdk update

### PR DESCRIPTION
**Pull request by augsteyer**
## Description

Updated SDK to fix issues with export characters. Also added a few tests to check for this.

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I updated the CHANGELOG.md

### CODE REVIEW

**Comment by Rekhyt** [comment]
Postman tests are missing the `m2_store` variable. Also, this seems to point to a store front rather than a store. Maybe rename to `m2_store_front_code` and default it to `default`?

**Comment by augsteyer** [comment]
it's in the  [globals](https://github.com/shopgate/cart-integration-magento2-base/blob/master/tests/Postman/globals.json#L55) . Yeah, the name is less than ideal. That I realized too when I was trying to find out what this variable is about 4 years after naming it ^_^ Also, I agree that globals may not be the best location for these m2 specifics.

**Comment by augsteyer** [comment]
Alrighty, I fixed the mentioned variable name. Apparently, I missed some renaming. The addOrder part still works, but partially. The postman mock server was designed to be called like this `mock.io/URL -> response 1`, and `mock.io/URL2 -> response 2`, but our SKD only makes calls to the same URL with different parameters `mock.io [action=get_orders, order_number=XXX] -> response 1`. So we kinda get Response 1 all the time.
Mock server part will need to be replaced as I mentioned earlier, however, it will require a good amount of work as there is more than 1 test with addOrder call. Removing them at this stage is not a good idea as they contain example responses that I will need to migrate these tests later. Any advice? :)

Here is an example of the mock setup:
image

**Comment by Rekhyt** [comment]
Variables confirmed fixed. I replaced the mocking of Merchant API with a workflow on pipedream.net. It reacts on order numbers `12345` (no coupon) and `54321` (with coupon `APP10`) or a simple JSON response if the request wasn't `get_orders`. Should be good for now.

Just FYI: Only test not working is synchronizing order cancellations to SG. That's unrelated to the PR, tough.

**Review by Rekhyt — APPROVED** [review]

**Pull request merged**
