### PR TITLE
Magento2-155 exclude_item_ids

### PR DESCRIPTION
**Pull request by Skistims**
forwarding exclude_item_ids setting

### CODE REVIEW

**Comment by augsteyer** [comment]
no branch name :(

**Review by augsteyer — APPROVED** [review]

**Comment by Skistims** [comment]
But I named the PR!

**Comment by augsteyer** [comment]
Well, the only reason why I care about the branch naming is that it helps me figure out what branch was fixing what and if I can remove it later or if I need to switch between PR's. Helps with the mess that accumulates, e.g.:
screen shot 2018-02-23 at 20 22 24

**Comment by Skistims** [comment]
Got it. Will remind it when I create branches in the future!

**Pull request merged**
